[tool.poetry]
name = "finder-chart-generator"
version = "0.1.0"
description = ""
authors = ["Christian Hettlage <hettlage@saao.ac.za>"]
readme = "README.md"
packages = [{include = "finder_chart_generator"}]

[tool.poetry.dependencies]
python = "^3.10"


[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
flake8 = "^6.0.0"
black = {extras = ["d"], version = "^23.3.0"}
isort = "^5.12.0"
flake8-bugbear = "^23.3.23"
flake8-print = "^5.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
