@Library('saao-shared-library@run-python-tests') _

pipeline {
  agent any

  stages {
    stage("Run tests") {
      steps {
        saaoRunPythonTests()
      }
    }
//     stage("Deploy the site") {
//       steps {
//         saaoDeployContainer(
//           host: "${FCG_DEV_HOST}",
//           hostCredentialsId: 'fcg-dev-server-credentials',
//           imageName: 'finder-chart-generator',
//           registryCredentialsId: 'docker-registry-credentials',
//           registryUrl: "${DOCKER_REGISTRY}"
//         )
//       }
//     }
  }

  post {
    always {
      cleanWs()
    }
  }
}
