@Library('saao-shared-library@run-python-tests') _

pipeline {
  agent {
    dockerfile {
      filename 'Dockerfile'
      dir 'jenkins/dev-deployment'
      args '-v finder-chart-generator-venv:/venv -u 0:0'
    }
  }

  stages {
    stage("Run tests") {
      steps {
        sh 'echo $PATH'
        sh 'poetry export -f requirements.txt --with dev --output requirements.txt'
        saaoRunPythonTests(
          'bandit': ['fcg'],
          'black': ['fcg', 'tests'],
          'flake8': ['fcg', 'tests'],
          'isort': ['fcg', 'tests'],
          'mypy': ['fcg', 'tests'],
          'pytest': ['tests']
        )
      }
    }
//     stage("Deploy the site") {
//       steps {
//         saaoDeployContainer(
//           host: "${FCG_DEV_HOST}",
//           hostCredentialsId: 'fcg-dev-server-credentials',
//           imageName: 'finder-chart-generator',
//           registryCredentialsId: 'docker-registry-credentials',
//           registryUrl: "${DOCKER_REGISTRY}"
//         )
//       }
//     }
  }

  post {
    always {
      cleanWs()
    }
  }
}
