@Library('saao-shared-library') _

pipeline {
  agent any

  stages {
    stage('Perform linting and testing') {
      agent {
        dockerfile {
          filename 'Dockerfile'
          dir 'jenkins'
          args '-v finder-chart-generator-poetry-cache:/root/.cache/pypoetry -u 0:0'
        }
      }

      steps {
        sh '''
        poetry add --group=dev allure-pytest
        poetry install
        '''
        script {
          success = saao.runPythonTests(
                  'bandit': ['fcg'],
                  'black': ['fcg', 'tests'],
                  'mypy': ['fcg', 'tests'],
                  'pytest': ['tests'],
                  'ruff': ['fcg', 'tests'],
                  'usePoetry': true
          )
          if (!success) {
            error('Linting and/or testing was unsuccessful.')
          }
        }
      }
    }

    stage('Deploy to production server') {
      when {
        branch 'main'
      }
      steps {
        script {
          saao.deployContainer(
                  'dockerComposeFile': 'docker-compose.yml',
                  'dockerFile': 'Dockerfile',
                  'host': 'ssdadev.cape.saao.ac.za',
                  'hostCredentialsId': 'finder_chart_generator_host',
                  'imageName': 'finder-chart-generator',
                  'registryCredentialsId': 'finder_chart_generator_registry',
                  'registryUrl': 'https://registry.salt.ac.za'
          )
        }
      }
    }
  }

  post {
    always {
      script {
        saao.generatePythonTestReports()
      }
    }
    changed {
      emailext(
              body: """The pipeline status has changed to ${currentBuild.result} for the $JOB_NAME pipeline.

See full details on ${env.BUILD_URL}.
""",
              subject: "[Jenkins :: $JOB_NAME] pipeline status changed",
              to: "$SALT_ASTROOPS_EMAIL"
      )
    }
  }
}
