@Library('saao-shared-library')

def config = [:]
def success = true

pipeline {
  agent any

  stages {
    stage("Read configuration data") {
      steps {
        script {
          configFileProvider([
            configFile(
              fileId: 'finder-chart-generator-dev',
              variable: 'FCG_CONFIG'
            )
          ]) {
             config = readJSON file: "$FCG_CONFIG"
          }
        }
      }
    }
    stage("Run tests") {
      agent {
        dockerfile {
          filename 'Dockerfile'
          dir 'jenkins/agent'
          args '-v finder-chart-generator-venv:/venv -u 0:0'
        }
      }
      steps {
        sh 'echo $PATH'
        sh 'poetry export -f requirements.txt --with dev --output requirements.txt'
        sh 'python -m pip install -r requirements.txt'
        script {
          success = saao.runPythonTests(
            "black": ["fcg", "tests"],
            "flake8": ["fcg", "tests"],
            "isort": ["fcg", "tests"],
            "mypy": ["fcg", "tests"],
            "pytest": ["tests"]
          )
        }
      }
    }
  }

  post {
    always {
      script {
        saao.generatePythonTestReports()
      }
    }
  }
}
