@Library('saao-shared-library')

def config = [:]
def success = true

pipeline {
  agent any

  stages {
    stage("Read configuration data") {
      steps {
        script {
          configFileProvider([
            configFile(
              fileId: 'finder-chart-generator-dev',
              variable: 'FCG_CONFIG'
            )
          ]) {
             config = readJSON file: "$FCG_CONFIG"
          }
        }
      }
    }
    stage("Use config") {
      echo "$config"
    }
  }

}
